### ISSUE TITLE
Prepare the user for which mini game is upcoming? 

### ISSUE THREAD

**Issue by ojdon** [DivineOmega/js13k#1]
During the pre-game scene? Possible solution as it isn't clear what to do when you should press the key without looking at the source code.

**Comment by ojdon** [comment]
Possible solution as it isn't clear what to do when you should press the key without looking at the source code.

**Comment by Jord-JD** [comment]
Controls have been added to the minigame switcher scene. Need to review whether this is appropriate.

**Comment by ojdon** [comment]
I think the issue has been resolved. I'll close for now.
